### ISSUE TITLE
2.0.0 regression: `AttributeError: 'Subscript' object has no attribute 'attr'`

### ISSUE THREAD

**Issue by The-Compiler** [gforcada/flake8-deprecated#19]
With a reproducer such as this:

```python
funcs = [print]
funcs[0]("Hello World")
```

running flake8-deprecated 2.0.0 fails with:

```pytb
Traceback (most recent call last):
  ...
  File "/home/florian/tmp/flake8-deprecated/flake8_deprecated.py", line 47, in run
    yield from value
  File "/home/florian/tmp/flake8-deprecated/flake8_deprecated.py", line 57, in check_calls
    yield from value
  File "/home/florian/tmp/flake8-deprecated/flake8_deprecated.py", line 70, in check_method_call
    method_name = node.func.attr
AttributeError: 'Subscript' object has no attribute 'attr'
```

Git bisect points to 52b754509f1ad4b37a9ead761ea44d26d29ae467 ("refactor: ensure all deprecations are detected").

**Comment by gforcada** [comment]
oh, wow, thanks for the report, and all the analysis 💯 I will try to have time in the next few days to fix it, if no one beats me at doing it 😉

**Comment by sminozhenko** [comment]
Got the same issue today in my project.

**Comment by gforcada** [comment]
@The-Compiler thanks again for the report, and specially for a small reproducible test, I used it verbatim on the test suite ✨ 💯 

A new release is out: __2.0.1__ please give it a try! 😄 hopefully this one is good to go on your source codes 🤞🏾

**Comment by sminozhenko** [comment]
> 

Thank you very much. Works for me!
